server:
  port: 8084

spring:
  application:
    name: auth-service
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
auth:
  provided-uri: "http://localhost:8084"
jks:
  keypass: 123456
  storepass: 123456
  alias: product
  path: keystore/product.jks
