server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:9090/realms/ecommerce-boari-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://localhost:9090/realms/ecommerce-boari-realm/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: auth-service
      principle-attribute: preferred_username
