spring:
  config:
    import: optional:secrets.properties
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

