server:
  port: 8082

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
