server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084
          jwk-set-uri: http://localhost:8084/oauth2/jwks

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

