server:
  port: 9297

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nicholasboari/demo-config-server.git
          clone-on-start: true